### ISSUE TITLE
Can't build on Python 3.7, no member named 'exc_value' in 'struct _ts'

### ISSUE THREAD

**Issue by mjpieters** [pynetwork/pypcap#89]
`pcap.c` accesses the current exception information directly on the `tstate` thread state struct, which [was changed in Python 3.7](https://github.com/python/cpython/commit/ae3087c6382011c47db82fea4d05f8bbf514265d). Attempting to build `pypcap` on Python 3.7 results in:

```
  pcap.c:22848:21: error: no member named 'exc_type' in 'struct _ts'
      *type = tstate->exc_type;
              ~~~~~~  ^
  pcap.c:22849:22: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
      *value = tstate->exc_value;
                       ^~~~~~~~~
                       curexc_value
  /Users/mj/Development/Library/buildout.python/parts/opt/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here
      PyObject *curexc_value;
                ^
  pcap.c:22850:19: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
      *tb = tstate->exc_traceback;
                    ^~~~~~~~~~~~~
                    curexc_traceback
  /Users/mj/Development/Library/buildout.python/parts/opt/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here
      PyObject *curexc_traceback;
                ^
  pcap.c:22857:24: error: no member named 'exc_type' in 'struct _ts'
      tmp_type = tstate->exc_type;
                 ~~~~~~  ^
  pcap.c:22858:25: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
      tmp_value = tstate->exc_value;
                          ^~~~~~~~~
                          curexc_value
  /Users/mj/Development/Library/buildout.python/parts/opt/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here
      PyObject *curexc_value;
                ^
  pcap.c:22859:22: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
      tmp_tb = tstate->exc_traceback;
                       ^~~~~~~~~~~~~
                       curexc_traceback
  /Users/mj/Development/Library/buildout.python/parts/opt/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here
      PyObject *curexc_traceback;
                ^
  pcap.c:22860:13: error: no member named 'exc_type' in 'struct _ts'
      tstate->exc_type = type;
      ~~~~~~  ^
  pcap.c:22861:13: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
      tstate->exc_value = value;
              ^~~~~~~~~
              curexc_value
  /Users/mj/Development/Library/buildout.python/parts/opt/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here
      PyObject *curexc_value;
                ^
  pcap.c:22862:13: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
      tstate->exc_traceback = tb;
              ^~~~~~~~~~~~~
              curexc_traceback
```

etc.

You probably should be using the [`PyErr_GetExcInfo()`](https://docs.python.org/3/c-api/exceptions.html#c.PyErr_GetExcInfo) and [`PyErr_SetExcInfo()`](https://docs.python.org/3/c-api/exceptions.html#c.PyErr_SetExcInfo) API functions to get and set this information.

**Comment by hellais** [comment]
Thanks for reporting this

**Comment by NearTan** [comment]
@hellais Hi, I have the same issue. Is there any plan to fix it? 😁

**Comment by lambdalisue** [comment]
This should be fixed with https://github.com/pynetwork/pypcap/pull/77

**Comment by polaris6933** [comment]
I'm hitting the same issue with cython 0.29.7 on Manjaro Linux. Tried installing from source and the result was the same.

**Comment by hellais** [comment]
This should be fixed with the latest release.
